apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lustre-meilisearch.fullname" . }}
  labels:
    {{- include "lustre-meilisearch.labels" . | nindent 4 }}
type: Opaque
data:
  master-key: {{ .Values.masterKey | b64enc }}
