replicaCount: 1

image:
  repository: nats
  tag: "2-alpine"
  pullPolicy: IfNotPresent

jetstream:
  enabled: true
  maxMemory: 256Mi
  maxStorage: 5Gi

persistence:
  size: 5Gi
  storageClass: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

service:
  type: ClusterIP
  clientPort: 4222
  monitorPort: 8222

livenessProbe:
  httpGet:
    path: /healthz
    port: 8222
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /healthz?js-enabled-only=true
    port: 8222
  initialDelaySeconds: 5
  periodSeconds: 10
