apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lustre-nats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: nats-client
    - port: {{ .Values.service.monitorPort }}
      targetPort: monitor
      protocol: TCP
      name: nats-monitor
  selector:
    {{- include "lustre-nats.selectorLabels" . | nindent 4 }}
