apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lustre-nats.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-nats
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lustre-nats.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lustre-nats.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config
            - /etc/nats/nats.conf
          ports:
            - containerPort: 4222
              name: client
              protocol: TCP
            - containerPort: 8222
              name: monitor
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/nats
            - name: jetstream-data
              mountPath: /data/jetstream
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-nats-config
  volumeClaimTemplates:
    - metadata:
        name: jetstream-data
        labels:
          {{- include "lustre-nats.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
