apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lustre-umami.fullname" . }}
  labels:
    {{ include "lustre-umami.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: umami
  template:
    metadata:
      labels:
        {{ include "lustre-umami.labels" . | nindent 8 }}
    spec:
      containers:
        - name: umami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lustre-secrets
                  key: database-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: lustre-secrets
                  key: umami-app-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
