apiVersion: v1
kind: Service
metadata:
  name: {{ include "lustre-umami.fullname" . }}
  labels:
    {{ include "lustre-umami.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: umami
