apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lustre-postgresql.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lustre-postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  {{- if .Values.backup.enabled }}
  R2_ACCESS_KEY_ID: {{ .Values.backup.rclone.accessKeyId | b64enc | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.backup.rclone.secretAccessKey | b64enc | quote }}
  R2_ENDPOINT: {{ .Values.backup.rclone.endpoint | b64enc | quote }}
  R2_BUCKET: {{ .Values.backup.rclone.bucket | b64enc | quote }}
  {{- end }}
