apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lustre-postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lustre-postgresql.labels" . | nindent 4 }}
